// ANGARA CLONE — Product Database (40 Rings)

const METAL_MULTIPLIERS = {
  '14K White Gold':  1.00,
  '18K White Gold':  1.15,
  '14K Yellow Gold': 1.02,
  '18K Yellow Gold': 1.18,
  '14K Rose Gold':   1.02,
  '18K Rose Gold':   1.15,
  'Platinum':        1.35,
};

const QUALITY_MULTIPLIERS = {
  'A':        0.80,
  'AA':       0.90,
  'AAA':      1.00,
  'Heirloom': 1.25,
};

const CARAT_MULTIPLIERS = {
  '0.34': 0.82,
  '0.52': 1.00,
  '0.70': 1.22,
  '0.88': 1.45,
  '1.00': 1.65,
  '1.20': 1.90,
};

const IMAGES = {
  sapphire:   'ring_sapphire_1775173368318.png',
  diamond:    'ring_diamond_1775173381818.png',
  emerald:    'ring_emerald_1775173397022.png',
  aquamarine: 'ring_aquamarine_1775173426942.png',
  ruby:       'ring_ruby_1775173443068.png',
  morganite:  'ring_morganite_1775173457195.png',
  tanzanite:  'ring_tanzanite_1775175245645.png',
  garnet:     'ring_garnet_1775175264227.png',
  amethyst:   'ring_amethyst_1775175279042.png',
  hand:       'ring_hand_lifestyle_1775175295636.png',
  side:       'ring_side_profile_1775175311559.png',
  dimension:  'ring_dimension_view_1775175410730.png',
};

const img = (key) => `assets/${IMAGES[key]}`;

const RINGS = [
  {
    id:1,slug:'solitaire-oval-opal-split-shank-ring',name:'Solitaire Oval Opal Split Shank Ring with Trio Diamonds',sku:'SR1375OPD',
    badge:'NEW ARRIVAL',gemstone:'Opal',gemColor:'#a8d4dc',shape:'Oval',style:'Solitaire',
    basePrice:1199,originalPrice:1499,rating:4.5,reviewCount:77,
    images:[img('aquamarine'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold','18K Rose Gold','Platinum'],
    qualities:['AAA','Heirloom'],caratOptions:['0.34','0.52','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'Heirloom',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5,9],
    swatchColors:['#a8d4dc','#c8e0c0','#d4b0a0'],
    description:'This 18K white gold opal ring with a unique split shank design looks exceedingly feminine and elegant. The prong-set oval opal entices with its beautiful color play that is accentuated by flanking trio diamonds.',
  },
  {
    id:2,slug:'classic-oval-blue-sapphire-halo-ring',name:'Classic Oval Blue Sapphire Ring with Diamond Halo',sku:'SR0902BSD',
    badge:'BEST SELLER',gemstone:'Blue Sapphire',gemColor:'#1a3f8f',shape:'Oval',style:'Halo',
    basePrice:1580,originalPrice:1899,rating:4.8,reviewCount:203,
    images:[img('sapphire'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5,9],
    swatchColors:['#1a3f8f','#2a6090','#3070b0'],
    description:'A timeless classic, this stunning blue sapphire halo ring is crafted in polished 18K white gold. The oval center stone is encircled by brilliant round diamonds for a breathtaking sparkle.',
  },
  {
    id:3,slug:'round-diamond-solitaire-pave-band-ring',name:'Round Diamond Solitaire Ring with Pavé Band',sku:'SR0441DIA',
    badge:null,gemstone:'Diamond',gemColor:'#e8f0f8',shape:'Round',style:'Solitaire',
    basePrice:2200,originalPrice:2599,rating:4.9,reviewCount:415,
    images:[img('diamond'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00','1.20'],
    defaultMetal:'Platinum',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[4,4.5,5,5.5,6,6.5,7,7.5,8,9],
    swatchColors:['#e8f0f8','#f0f0f0','#e0e8f0'],
    description:'Breathtakingly brilliant, this classic round diamond solitaire sits atop a delicate pavé-set band. Crafted in platinum for lasting shine.',
  },
  {
    id:4,slug:'vintage-emerald-cut-emerald-ring',name:'Vintage Emerald Cut Emerald Ring with Side Stones',sku:'SR0887EMD',
    badge:'NEW ARRIVAL',gemstone:'Emerald',gemColor:'#1a7a40',shape:'Emerald Cut',style:'Vintage',
    basePrice:1750,originalPrice:2100,rating:4.6,reviewCount:88,
    images:[img('emerald'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K Yellow Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a7a40','#258050','#30905e'],
    description:'Inspired by Art Deco elegance, this vintage emerald ring features a rich green emerald cut stone flanked by sparkling diamond side stones.',
  },
  {
    id:5,slug:'pear-shaped-aquamarine-bypass-ring',name:'Pear-Shaped Aquamarine Bypass Ring with Diamonds',sku:'SR1021AQM',
    badge:null,gemstone:'Aquamarine',gemColor:'#5bc8e8',shape:'Pear',style:'Fashion',
    basePrice:980,originalPrice:1199,rating:4.7,reviewCount:134,
    images:[img('aquamarine'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','14K Rose Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.34','0.52','0.70'],
    defaultMetal:'14K White Gold',defaultQuality:'AAA',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5bc8e8','#4ab8d8','#7adcf0'],
    description:'A refreshing oceanic statement, this pear-shaped aquamarine bypass ring features a flowing design that gracefully wraps the finger.',
  },
  {
    id:6,slug:'oval-ruby-diamond-halo-ring',name:'Oval Ruby Ring with Diamond Halo in Rose Gold',sku:'SR0678RBY',
    badge:'BEST SELLER',gemstone:'Ruby',gemColor:'#c0182a',shape:'Oval',style:'Halo',
    basePrice:1890,originalPrice:2299,rating:4.8,reviewCount:167,
    images:[img('ruby'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','14K Rose Gold','18K Rose Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5],
    swatchColors:['#c0182a','#d02838','#b01022'],
    description:'Passionately bold, this oval ruby halo ring in rose gold creates a romantic pairing of deep red and warm gold.',
  },
  {
    id:7,slug:'pear-morganite-diamond-halo-ring',name:'Pear-Shaped Morganite Halo Ring in Rose Gold',sku:'SR0892MGN',
    badge:'NEW ARRIVAL',gemstone:'Morganite',gemColor:'#f0a8a0',shape:'Pear',style:'Halo',
    basePrice:1050,originalPrice:1299,rating:4.7,reviewCount:98,
    images:[img('morganite'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','14K Yellow Gold','14K Rose Gold','18K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','1.00'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#f0a8a0','#f8b8b0','#e89898'],
    description:'Soft, romantic, and ethereal — this pear-shaped morganite halo ring is a declaration of love in blush-pink and rose gold.',
  },
  {
    id:8,slug:'oval-tanzanite-three-stone-ring',name:'Oval Tanzanite Three Stone Ring with Diamond Accents',sku:'SR1102TZN',
    badge:null,gemstone:'Tanzanite',gemColor:'#5040c0',shape:'Oval',style:'Three Stone',
    basePrice:1650,originalPrice:1999,rating:4.6,reviewCount:56,
    images:[img('tanzanite'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5040c0','#6050d0','#7060e0'],
    description:"Tanzanite's extraordinary trichroic violet-blue hues shine brilliantly in this trinity setting — a true collector's gemstone.",
  },
  {
    id:9,slug:'round-garnet-solitaire-ring',name:'Round Garnet Solitaire Ring in Yellow Gold',sku:'SR0445GRN',
    badge:null,gemstone:'Garnet',gemColor:'#8b1020',shape:'Round',style:'Solitaire',
    basePrice:690,originalPrice:850,rating:4.5,reviewCount:112,
    images:[img('garnet'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['A','AA','AAA'],caratOptions:['0.34','0.52','0.70'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AA',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5,9],
    swatchColors:['#8b1020','#9b2030','#7b0010'],
    description:'Bold and fiery, this round garnet solitaire showcases the deep crimson warmth of premium Bohemian garnets in elegant 14K yellow gold.',
  },
  {
    id:10,slug:'cushion-amethyst-vintage-ring',name:'Cushion Cut Amethyst Vintage Ring with Diamond Border',sku:'SR0711AMT',
    badge:null,gemstone:'Amethyst',gemColor:'#7030b0',shape:'Cushion',style:'Vintage',
    basePrice:890,originalPrice:1099,rating:4.6,reviewCount:73,
    images:[img('amethyst'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#7030b0','#8040c0','#6020a0'],
    description:'Steeped in vintage charm, this cushion-cut amethyst ring features intricate milgrain borders and pave-set diamonds.',
  },
  {
    id:11,slug:'heart-sapphire-halo-ring',name:'Heart-Shaped Blue Sapphire Halo Ring',sku:'SR1201BSH',
    badge:null,gemstone:'Blue Sapphire',gemColor:'#1a3f8f',shape:'Heart',style:'Halo',
    basePrice:1420,originalPrice:1699,rating:4.7,reviewCount:91,
    images:[img('sapphire'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Rose Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a3f8f','#2050a0'],
    description:'Express your love with this heart-shaped blue sapphire halo ring, radiating romance and elegance from every angle.',
  },
  {
    id:12,slug:'princess-cut-diamond-engagement-ring',name:'Princess Cut Diamond Engagement Ring',sku:'SR0322DPR',
    badge:'BEST SELLER',gemstone:'Diamond',gemColor:'#e8f0f8',shape:'Princess',style:'Solitaire',
    basePrice:2800,originalPrice:3299,rating:4.9,reviewCount:388,
    images:[img('diamond'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AAA','Heirloom'],caratOptions:['0.70','0.88','1.00','1.20'],
    defaultMetal:'Platinum',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[4,4.5,5,5.5,6,6.5,7,7.5,8,9],
    swatchColors:['#e8f0f8','#d8e8f0'],
    description:'The princess cut diamond is the most popular fancy-cut, prized for its modern geometric beauty and exceptional brilliance.',
  },
  {
    id:13,slug:'oval-emerald-three-stone-ring',name:'Oval Emerald Three Stone Ring',sku:'SR0993EMT',
    badge:null,gemstone:'Emerald',gemColor:'#1a7a40',shape:'Oval',style:'Three Stone',
    basePrice:1600,originalPrice:1950,rating:4.5,reviewCount:62,
    images:[img('emerald'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a7a40','#208050'],
    description:'Three oval emeralds in a trinity setting symbolize past, present, and future — perfect for a meaningful commitment ring.',
  },
  {
    id:14,slug:'round-ruby-eternity-band',name:'Round Ruby Eternity Band Ring',sku:'SR1310RBE',
    badge:null,gemstone:'Ruby',gemColor:'#c0182a',shape:'Round',style:'Eternity',
    basePrice:2100,originalPrice:2599,rating:4.8,reviewCount:145,
    images:[img('ruby'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AA','AAA'],caratOptions:['0.70','1.00','1.20'],
    defaultMetal:'14K White Gold',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#c0182a','#d02030'],
    description:'A stunning full eternity band featuring lustrous red rubies circling the finger in an unbroken symbol of eternal love.',
  },
  {
    id:15,slug:'morganite-solitaire-rose-gold-ring',name:'Morganite Solitaire Ring in Rose Gold',sku:'SR0788MGS',
    badge:null,gemstone:'Morganite',gemColor:'#f0a8a0',shape:'Oval',style:'Solitaire',
    basePrice:780,originalPrice:950,rating:4.6,reviewCount:189,
    images:[img('morganite'),img('hand'),img('side')],
    metals:['14K Rose Gold','18K Rose Gold','14K White Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','1.00'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#f0a8a0','#f8b8b0'],
    description:'Breathtakingly delicate, this morganite solitaire in rose gold channels soft femininity through blush-pink hues and refined simplicity.',
  },
  {
    id:16,slug:'marquise-aquamarine-accent-ring',name:'Marquise Aquamarine Ring with Diamond Accents',sku:'SR1044AQM',
    badge:'NEW ARRIVAL',gemstone:'Aquamarine',gemColor:'#5bc8e8',shape:'Marquise',style:'Side Stone',
    basePrice:1100,originalPrice:1399,rating:4.5,reviewCount:44,
    images:[img('aquamarine'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5bc8e8','#7adcf0'],
    description:'The elongated marquise cut enhances the mesmerizing blue of aquamarine, flanked by brilliant diamond accents for a regal look.',
  },
  {
    id:17,slug:'oval-tanzanite-diamond-halo-ring',name:'Oval Tanzanite Diamond Halo Ring',sku:'SR1108TZH',
    badge:null,gemstone:'Tanzanite',gemColor:'#5040c0',shape:'Oval',style:'Halo',
    basePrice:1890,originalPrice:2299,rating:4.7,reviewCount:78,
    images:[img('tanzanite'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5040c0','#7060e0'],
    description:"Tanzanite's extraordinary trichroic blue-violet hues are showcased brilliantly in this diamond halo ring — a true collector's gemstone.",
  },
  {
    id:18,slug:'round-amethyst-halo-ring',name:'Round Amethyst Ring with Diamond Halo',sku:'SR0722AMH',
    badge:null,gemstone:'Amethyst',gemColor:'#7030b0',shape:'Round',style:'Halo',
    basePrice:950,originalPrice:1199,rating:4.6,reviewCount:117,
    images:[img('amethyst'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','14K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'14K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#7030b0','#8040c0'],
    description:'The deep purple amethyst is the birthstone of February and a symbol of peace, set here in a brilliant diamond halo for added sparkle.',
  },
  {
    id:19,slug:'cushion-sapphire-split-shank-ring',name:'Cushion Blue Sapphire Split Shank Ring',sku:'SR0911BSC',
    badge:null,gemstone:'Blue Sapphire',gemColor:'#1a3f8f',shape:'Cushion',style:'Side Stone',
    basePrice:1750,originalPrice:2099,rating:4.8,reviewCount:159,
    images:[img('sapphire'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.88',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a3f8f','#2a50a0'],
    description:'The cushion-cut combines soft square shape with rounded corners for a romantic vintage feel. This sapphire version is the choice of royalty.',
  },
  {
    id:20,slug:'pear-shaped-garnet-ring',name:'Pear-Shaped Garnet Ring with Diamond Side Stones',sku:'SR0458GRP',
    badge:null,gemstone:'Garnet',gemColor:'#8b1020',shape:'Pear',style:'Side Stone',
    basePrice:780,originalPrice:960,rating:4.4,reviewCount:83,
    images:[img('garnet'),img('hand'),img('side')],
    metals:['14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['A','AA','AAA'],caratOptions:['0.34','0.52','0.70'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AA',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#8b1020','#9b2030'],
    description:'The pear-shaped garnet has an aristocratic silhouette with diamond side stones adding sparkle to the deep red center.',
  },
  {
    id:21,slug:'round-emerald-vintage-milgrain-ring',name:'Round Emerald Vintage Milgrain Ring',sku:'SR0870EVM',
    badge:null,gemstone:'Emerald',gemColor:'#1a7a40',shape:'Round',style:'Vintage',
    basePrice:1350,originalPrice:1650,rating:4.5,reviewCount:68,
    images:[img('emerald'),img('hand'),img('side')],
    metals:['14K White Gold','14K Yellow Gold','18K Yellow Gold'],
    qualities:['AA','AAA'],caratOptions:['0.52','0.70'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AA',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a7a40','#258050'],
    description:'Intricate milgrain detailing frames this round emerald in a celebration of Edwardian jewelry craftsmanship.',
  },
  {
    id:22,slug:'oval-ruby-vintage-engagement-ring',name:'Oval Ruby Vintage Engagement Ring',sku:'SR0689RBV',
    badge:null,gemstone:'Ruby',gemColor:'#c0182a',shape:'Oval',style:'Vintage',
    basePrice:1950,originalPrice:2399,rating:4.7,reviewCount:102,
    images:[img('ruby'),img('hand'),img('side')],
    metals:['14K Yellow Gold','18K Yellow Gold','14K Rose Gold','18K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K Yellow Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#c0182a','#d02838'],
    description:'Romance meets tradition in this oval ruby vintage engagement ring with intricate hand-engraved filigree sides.',
  },
  {
    id:23,slug:'cushion-morganite-engagement-ring',name:'Cushion Morganite Engagement Ring with Pave Band',sku:'SR0901MGE',
    badge:'NEW ARRIVAL',gemstone:'Morganite',gemColor:'#f0a8a0',shape:'Cushion',style:'Side Stone',
    basePrice:1100,originalPrice:1399,rating:4.8,reviewCount:222,
    images:[img('morganite'),img('hand'),img('side')],
    metals:['14K White Gold','14K Rose Gold','18K Rose Gold'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.70','1.00','1.20'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#f0a8a0','#f8c0b8'],
    description:'A modern classic — this cushion morganite engagement ring blends rose gold warmth with blush pink softness.',
  },
  {
    id:24,slug:'round-aquamarine-three-stone-ring',name:'Round Aquamarine Three Stone Ring',sku:'SR1030AQT',
    badge:null,gemstone:'Aquamarine',gemColor:'#5bc8e8',shape:'Round',style:'Three Stone',
    basePrice:1050,originalPrice:1299,rating:4.5,reviewCount:91,
    images:[img('aquamarine'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AA','AAA'],caratOptions:['0.52','0.70'],
    defaultMetal:'18K White Gold',defaultQuality:'AA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5bc8e8','#4ab8d8'],
    description:'Three perfectly matched aquamarines represent commitment, loyalty, and eternal love in a timeless trinity setting.',
  },
  {
    id:25,slug:'oval-diamond-halo-ring',name:'Oval Cut Diamond Halo Ring in White Gold',sku:'SR0512DOH',
    badge:'BEST SELLER',gemstone:'Diamond',gemColor:'#e8f0f8',shape:'Oval',style:'Halo',
    basePrice:3200,originalPrice:3899,rating:5.0,reviewCount:511,
    images:[img('diamond'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AAA','Heirloom'],caratOptions:['0.70','0.88','1.00','1.20'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[4,4.5,5,5.5,6,6.5,7,7.5,8,9],
    swatchColors:['#e8f0f8','#f0f8ff'],
    description:'The oval diamond halo ring is among our most beloved — the elongated shape creates the illusion of a larger center stone surrounded by a glittering halo.',
  },
  {
    id:26,slug:'emerald-cut-tanzanite-ring',name:'Emerald Cut Tanzanite Ring with Diamond Accents',sku:'SR1115TZE',
    badge:null,gemstone:'Tanzanite',gemColor:'#5040c0',shape:'Emerald Cut',style:'Side Stone',
    basePrice:1700,originalPrice:2099,rating:4.6,reviewCount:50,
    images:[img('tanzanite'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5040c0','#6050d0'],
    description:"The clean lines of the emerald cut showcase tanzanite's extraordinary color shift from violet to blue under different lighting.",
  },
  {
    id:27,slug:'round-garnet-band-ring',name:'Round Garnet Stackable Band Ring',sku:'SR0461GRB',
    badge:null,gemstone:'Garnet',gemColor:'#8b1020',shape:'Round',style:'Stackable',
    basePrice:550,originalPrice:699,rating:4.4,reviewCount:128,
    images:[img('garnet'),img('hand'),img('side')],
    metals:['14K White Gold','14K Yellow Gold','14K Rose Gold'],
    qualities:['A','AA'],caratOptions:['0.34','0.52'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AA',defaultCarat:'0.34',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#8b1020','#7b0010'],
    description:'Versatile and chic, this garnet stackable band pairs beautifully with other rings or stands alone as a bold statement.',
  },
  {
    id:28,slug:'oval-sapphire-three-stone-ring',name:'Oval Sapphire Three Stone Diamond Ring',sku:'SR0925BST',
    badge:null,gemstone:'Blue Sapphire',gemColor:'#1a3f8f',shape:'Oval',style:'Three Stone',
    basePrice:2100,originalPrice:2599,rating:4.8,reviewCount:177,
    images:[img('sapphire'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.88',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5],
    swatchColors:['#1a3f8f','#2050a0'],
    description:'Diana, Princess of Wales made the sapphire three-stone ring iconic. Own a piece modeled on this legendary heritage.',
  },
  {
    id:29,slug:'pear-shaped-amethyst-ring',name:'Pear-Shaped Amethyst Ring in Yellow Gold',sku:'SR0729AMP',
    badge:null,gemstone:'Amethyst',gemColor:'#7030b0',shape:'Pear',style:'Solitaire',
    basePrice:760,originalPrice:950,rating:4.5,reviewCount:86,
    images:[img('amethyst'),img('hand'),img('side')],
    metals:['14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['AA','AAA'],caratOptions:['0.52','0.70'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#7030b0','#6020a0'],
    description:'Dramatic and bold, the pear-shaped amethyst solitaire elongates the finger with its pointed tip and rounded base.',
  },
  {
    id:30,slug:'round-morganite-three-stone-ring',name:'Round Morganite Three Stone Ring',sku:'SR0810MGT',
    badge:null,gemstone:'Morganite',gemColor:'#f0a8a0',shape:'Round',style:'Three Stone',
    basePrice:890,originalPrice:1099,rating:4.6,reviewCount:155,
    images:[img('morganite'),img('hand'),img('side')],
    metals:['14K White Gold','14K Rose Gold','18K Rose Gold'],
    qualities:['AA','AAA'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#f0a8a0','#f8b8b0'],
    description:'Three blush-pink morganites in a harmonious trinity create a dreamy, romantic ring with undeniable ethereal beauty.',
  },
  {
    id:31,slug:'princess-cut-blue-sapphire-ring',name:'Princess Cut Blue Sapphire Ring with Pave Band',sku:'SR0918BSP',
    badge:null,gemstone:'Blue Sapphire',gemColor:'#1a3f8f',shape:'Princess',style:'Side Stone',
    basePrice:1650,originalPrice:1999,rating:4.7,reviewCount:103,
    images:[img('sapphire'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#1a3f8f','#2a5090'],
    description:'The geometric princess cut delivers bold modernity while the blue sapphire projects timeless luxury.',
  },
  {
    id:32,slug:'oval-diamond-three-stone-ring',name:'Oval Diamond Three Stone Ring in Platinum',sku:'SR0543DOT',
    badge:null,gemstone:'Diamond',gemColor:'#e8f0f8',shape:'Oval',style:'Three Stone',
    basePrice:4100,originalPrice:4999,rating:4.9,reviewCount:287,
    images:[img('diamond'),img('hand'),img('side'),img('dimension')],
    metals:['18K White Gold','Platinum'],
    qualities:['AAA','Heirloom'],caratOptions:['0.88','1.00','1.20'],
    defaultMetal:'Platinum',defaultQuality:'Heirloom',defaultCarat:'1.00',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#e8f0f8','#f0f4f8'],
    description:'An unmatched trio of oval diamonds in platinum — the ultimate engagement ring for those who believe more is more.',
  },
  {
    id:33,slug:'cushion-ruby-halo-ring',name:'Cushion Ruby Halo Ring in White Gold',sku:'SR0692RBC',
    badge:null,gemstone:'Ruby',gemColor:'#c0182a',shape:'Cushion',style:'Halo',
    basePrice:2200,originalPrice:2699,rating:4.8,reviewCount:131,
    images:[img('ruby'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#c0182a','#b01020'],
    description:'The cushion-cut ruby in white gold creates a striking contrast of vivid crimson against icy light — a breathtaking centerpiece.',
  },
  {
    id:34,slug:'round-aquamarine-eternity-ring',name:'Round Aquamarine Eternity Ring',sku:'SR1055AQE',
    badge:null,gemstone:'Aquamarine',gemColor:'#5bc8e8',shape:'Round',style:'Eternity',
    basePrice:1600,originalPrice:1950,rating:4.6,reviewCount:74,
    images:[img('aquamarine'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AA','AAA'],caratOptions:['0.70','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AA',defaultCarat:'1.00',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5bc8e8','#7adcf0'],
    description:'A complete circle of aquamarines circling the finger in an unbroken stream of ocean-blue beauty — the perfect anniversary band.',
  },
  {
    id:35,slug:'oval-tanzanite-solitaire-ring',name:'Oval Tanzanite Solitaire Ring',sku:'SR1105TZS',
    badge:null,gemstone:'Tanzanite',gemColor:'#5040c0',shape:'Oval',style:'Solitaire',
    basePrice:1400,originalPrice:1699,rating:4.5,reviewCount:41,
    images:[img('tanzanite'),img('hand'),img('side')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#5040c0','#7060e0'],
    description:'Let the tanzanite speak for itself in this clean, elegant solitaire setting — unobstructed beauty in its purest form.',
  },
  {
    id:36,slug:'round-garnet-three-stone-ring',name:'Round Garnet Three Stone Ring in Gold',sku:'SR0463GRT',
    badge:null,gemstone:'Garnet',gemColor:'#8b1020',shape:'Round',style:'Three Stone',
    basePrice:820,originalPrice:1050,rating:4.4,reviewCount:67,
    images:[img('garnet'),img('hand'),img('side')],
    metals:['14K Yellow Gold','18K Yellow Gold','14K Rose Gold'],
    qualities:['A','AA','AAA'],caratOptions:['0.34','0.52','0.70'],
    defaultMetal:'14K Yellow Gold',defaultQuality:'AA',defaultCarat:'0.52',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#8b1020','#9b2030'],
    description:'Three deep red garnets in a classic three-stone setting symbolizing past, present, and a passionate future.',
  },
  {
    id:37,slug:'oval-emerald-halo-ring',name:'Oval Emerald Halo Engagement Ring',sku:'SR0905EMH',
    badge:'BEST SELLER',gemstone:'Emerald',gemColor:'#1a7a40',shape:'Oval',style:'Halo',
    basePrice:2000,originalPrice:2499,rating:4.9,reviewCount:208,
    images:[img('emerald'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.88',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8,8.5],
    swatchColors:['#1a7a40','#30905e'],
    description:"A vivid green oval emerald encircled by a halo of white diamonds — nature's finest gem in its most magnificent setting.",
  },
  {
    id:38,slug:'cushion-amethyst-solitaire-ring',name:'Cushion Amethyst Solitaire Ring in Rose Gold',sku:'SR0715AMS',
    badge:null,gemstone:'Amethyst',gemColor:'#7030b0',shape:'Cushion',style:'Solitaire',
    basePrice:680,originalPrice:850,rating:4.6,reviewCount:94,
    images:[img('amethyst'),img('hand'),img('side')],
    metals:['14K White Gold','14K Yellow Gold','14K Rose Gold'],
    qualities:['AA','AAA'],caratOptions:['0.52','0.70','0.88'],
    defaultMetal:'14K Rose Gold',defaultQuality:'AA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#7030b0','#8040c0'],
    description:'A soft cushion-cut amethyst in rose gold creates an unexpectedly harmonious blend of cool violet and warm rose.',
  },
  {
    id:39,slug:'pear-diamond-solitaire-ring',name:'Pear Diamond Solitaire Engagement Ring',sku:'SR0524DPS',
    badge:null,gemstone:'Diamond',gemColor:'#e8f0f8',shape:'Pear',style:'Solitaire',
    basePrice:2900,originalPrice:3499,rating:4.9,reviewCount:344,
    images:[img('diamond'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','Platinum'],
    qualities:['AAA','Heirloom'],caratOptions:['0.70','0.88','1.00','1.20'],
    defaultMetal:'Platinum',defaultQuality:'AAA',defaultCarat:'1.00',
    sizeOptions:[4,4.5,5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#e8f0f8','#d8e8f8'],
    description:'The pear diamond — also called the teardrop — is an exquisitely feminine shape. This minimal solitaire lets its brilliance take center stage.',
  },
  {
    id:40,slug:'oval-ruby-three-stone-ring',name:'Oval Ruby Three Stone Ring with Diamond Accents',sku:'SR0701RBT',
    badge:'NEW ARRIVAL',gemstone:'Ruby',gemColor:'#c0182a',shape:'Oval',style:'Three Stone',
    basePrice:2450,originalPrice:2999,rating:4.8,reviewCount:119,
    images:[img('ruby'),img('hand'),img('side'),img('dimension')],
    metals:['14K White Gold','18K White Gold','14K Yellow Gold','18K Yellow Gold','14K Rose Gold','Platinum'],
    qualities:['AA','AAA','Heirloom'],caratOptions:['0.52','0.70','0.88','1.00'],
    defaultMetal:'18K White Gold',defaultQuality:'AAA',defaultCarat:'0.70',
    sizeOptions:[5,5.5,6,6.5,7,7.5,8],
    swatchColors:['#c0182a','#d02838'],
    description:"A trio of oval rubies embody life's richest moments — bold, passionate, and deeply meaningful. Diamond accents frame each stone in brilliant light.",
  },
];

// Helper Functions
function calculatePrice(ring, metal, quality, carat) {
  return Math.round(ring.basePrice * (METAL_MULTIPLIERS[metal]||1) * (QUALITY_MULTIPLIERS[quality]||1) * (CARAT_MULTIPLIERS[carat]||1));
}
function getOriginalPrice(ring, metal, quality, carat) {
  return Math.round(calculatePrice(ring, metal, quality, carat) * 1.25);
}
function formatPrice(n) { return '$' + n.toLocaleString('en-US'); }
function getRingById(id) { return RINGS.find(r => r.id === parseInt(id)) || null; }

const METAL_FILTERS = {
  '14K White Gold':  'brightness(1.05)',
  '18K White Gold':  'brightness(1.08) contrast(1.02)',
  '14K Yellow Gold': 'sepia(0.55) saturate(2.8) hue-rotate(4deg) brightness(1.06)',
  '18K Yellow Gold': 'sepia(0.65) saturate(3.0) hue-rotate(3deg) brightness(1.08)',
  '14K Rose Gold':   'sepia(0.45) saturate(2.2) hue-rotate(342deg) brightness(1.04)',
  '18K Rose Gold':   'sepia(0.55) saturate(2.5) hue-rotate(340deg) brightness(1.06)',
  'Platinum':        'grayscale(0.25) brightness(1.1) contrast(1.05)',
};
function getMetalFilter(metal) { return METAL_FILTERS[metal] || 'none'; }

const METAL_SWATCH_COLORS = {
  '14K White Gold': '#e8e0d0', '18K White Gold': '#f0e8d8',
  '14K Yellow Gold':'#d4a840', '18K Yellow Gold':'#e0b848',
  '14K Rose Gold':  '#d4906a', '18K Rose Gold':  '#e09c78',
  'Platinum':       '#c8c8d8',
};
function getMetalSwatchColor(metal) { return METAL_SWATCH_COLORS[metal] || '#ccc'; }
