// TSUKIYO GEMS — Professional Product Database
// Real product catalog with photographed inventory
// Last Updated: May 2026

const METAL_MULTIPLIERS = {
  '14K White Gold':  1.00,
  '18K White Gold':  1.15,
  '14K Yellow Gold': 1.02,
  '18K Yellow Gold': 1.18,
  '14K Rose Gold':   1.02,
  '18K Rose Gold':   1.15,
  'Sterling Silver': 0.45,
  'Platinum':        1.35,
};

const QUALITY_MULTIPLIERS = {
  'Good (A)':      0.80,
  'Better (AA)':   0.90,
  'Best (AAA)':    1.00,
  'Heirloom (AAAA)': 1.25,
};

const CARAT_MULTIPLIERS = {
  '0.34': 0.82,
  '0.52': 1.00,
  '0.70': 1.22,
  '0.88': 1.45,
  '1.00': 1.65,
  '1.20': 1.90,
  '1.50': 2.25,
  '2.00': 2.80,
};

// ----- Shared option presets -----
const STD_SIZES = [4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9];
const WIDE_SIZES = [4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10];
const MEN_SIZES = [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12];

const RINGS = [
  // ============================================================
  //  HALO OPAL & SAPPHIRE COLLECTION  (Silver / White Gold)
  // ============================================================
  {
    id: 1,
    slug: 'lightning-ridge-opal-halo-ring',
    name: 'Lightning Ridge Opal Halo Diamond Ring',
    sku: 'TG-OPL-101',
    badge: 'NEW ARRIVAL',
    gemstone: 'Opal',
    gemColor: '#d8c060',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 2480,
    originalPrice: 2899,
    rating: 4.9,
    reviewCount: 152,
    images: ['assets/rings/IMG_9141.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)', 'Heirloom (AAAA)'],
    caratOptions: ['0.52', '0.70', '0.88', '1.00'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.70',
    sizeOptions: STD_SIZES,
    swatchColors: ['#d8c060', '#b8d8c0', '#e8d8a0', '#e8f0f8'],
    description: 'A radiant halo ring centered on a natural Australian opal from the famed Lightning Ridge fields, alive with a yellow-and-green play of colour. The center stone is encircled by a ring of pavé diamonds that magnifies the opal\'s fire. Set in a cool white-toned shank, this is a unique alternative engagement ring or a true keepsake cocktail piece. Opal is October\'s birthstone and has long symbolised hope, creativity, and faithfulness.',
    specifications: {
      stoneType: 'Natural Solid Australian Opal',
      stoneOrigin: 'Lightning Ridge, NSW',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '1.8–2.6 ct',
      diamondQuality: 'VS clarity, F-G colour',
      settingStyle: 'Halo with Pavé Accents',
      careInstructions: 'Avoid prolonged heat, dry environments and heavy chemicals. Clean with a soft cloth and warm soapy water; never ultrasonic.'
    }
  },
  {
    id: 2,
    slug: 'green-opal-halo-cocktail-ring',
    name: 'Green Fire Opal Halo Cocktail Ring',
    sku: 'TG-OPL-102',
    badge: 'BEST SELLER',
    gemstone: 'Opal',
    gemColor: '#7fbf85',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 2890,
    originalPrice: 3399,
    rating: 4.8,
    reviewCount: 184,
    images: ['assets/rings/IMG_9142.jpg', 'assets/rings/IMG_9151.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)', 'Heirloom (AAAA)'],
    caratOptions: ['0.70', '0.88', '1.00', '1.20'],
    defaultMetal: '18K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.88',
    sizeOptions: STD_SIZES,
    swatchColors: ['#7fbf85', '#5fb088', '#9fe0a2', '#e8f0f8'],
    description: 'A spectacular green-fire opal cabochon set in a brilliant diamond halo. The opal flashes vivid greens, blues and gold from every angle, an effect known as "play of colour." The bright halo of pavé diamonds and a polished tapered shank make the centre stone the star of the piece. A sophisticated alternative for those who want colour and individuality without sacrificing classic elegance.',
    specifications: {
      stoneType: 'Natural Solid Black Opal',
      stoneOrigin: 'Lightning Ridge, NSW',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '2.2–3.0 ct',
      diamondQuality: 'VS-SI clarity, G-H colour',
      settingStyle: 'Pavé Halo on Tapered Shank',
      careInstructions: 'Remove during heavy work or sport. Clean gently with a damp soft cloth.'
    }
  },
  {
    id: 3,
    slug: 'sapphire-baguette-halo-ring',
    name: 'Blue Sapphire Baguette Halo Ring',
    sku: 'TG-SPH-201',
    badge: 'BEST SELLER',
    gemstone: 'Sapphire',
    gemColor: '#1a3f8f',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 3450,
    originalPrice: 3999,
    rating: 4.9,
    reviewCount: 221,
    images: ['assets/rings/IMG_9145.jpg', 'assets/rings/IMG_9148.jpg', 'assets/rings/IMG_9149.jpg'],
    metals: ['14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)', 'Heirloom (AAAA)'],
    caratOptions: ['0.70', '0.88', '1.00', '1.20', '1.50'],
    defaultMetal: '18K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#1a3f8f', '#2a55a0', '#3070b0', '#e8f0f8'],
    description: 'A crisp royal-blue sapphire centres this engagement-worthy cocktail ring, flanked by tapered baguette diamonds and edged in a fine pavé halo. The combination of step-cut accents and a brilliant centre stone creates an Art Deco-meets-modern profile. Sapphire (corundum) sits at 9 Mohs — second only to diamond in hardness — which makes this ring a beautiful daily-wear option as well as a special-occasion statement.',
    specifications: {
      stoneType: 'Natural Blue Sapphire (Corundum)',
      stoneOrigin: 'Sri Lanka or Madagascar',
      stoneHardness: '9 Mohs',
      centerStoneApproxCarat: '1.8–2.5 ct',
      diamondQuality: 'VS clarity, F-G colour',
      settingStyle: 'Halo with Baguette Side Stones',
      careInstructions: 'Excellent for daily wear. Clean with warm soapy water or an ultrasonic cleaner.'
    }
  },
  {
    id: 4,
    slug: 'sapphire-pave-halo-cocktail-ring',
    name: 'Royal Blue Sapphire Pavé Halo Ring',
    sku: 'TG-SPH-202',
    badge: null,
    gemstone: 'Sapphire',
    gemColor: '#1d3a78',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 2780,
    originalPrice: 3299,
    rating: 4.7,
    reviewCount: 96,
    images: ['assets/rings/IMG_9146.jpg', 'assets/rings/IMG_9170.jpg'],
    metals: ['14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.70', '0.88', '1.00', '1.20'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.88',
    sizeOptions: STD_SIZES,
    swatchColors: ['#1d3a78', '#1a3f8f', '#3070b0', '#e8f0f8'],
    description: 'A rich royal-blue sapphire centres this dramatic halo cocktail ring, completely surrounded by a generous pavé crown of micro-set diamonds. The shank is tapered and finished in a high polish to throw maximum light at the centre. A timeless silhouette that suits engagements, anniversaries and red-carpet evenings alike.',
    specifications: {
      stoneType: 'Natural Blue Sapphire',
      stoneOrigin: 'Sri Lanka',
      stoneHardness: '9 Mohs',
      centerStoneApproxCarat: '1.8–2.4 ct',
      diamondQuality: 'VS-SI clarity, G colour',
      settingStyle: 'Pavé Halo, Tapered Shank',
      careInstructions: 'Clean with warm soapy water. Ultrasonic safe. Inspect prongs annually.'
    }
  },
  {
    id: 5,
    slug: 'black-opal-halo-engagement-ring',
    name: 'Black Opal Halo Engagement Ring',
    sku: 'TG-OPL-103',
    badge: 'NEW ARRIVAL',
    gemstone: 'Opal',
    gemColor: '#1a2a3a',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 3290,
    originalPrice: 3899,
    rating: 4.9,
    reviewCount: 147,
    images: ['assets/rings/IMG_9147.jpg', 'assets/rings/IMG_9150.jpg'],
    metals: ['14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)', 'Heirloom (AAAA)'],
    caratOptions: ['0.88', '1.00', '1.20', '1.50'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#1a2a3a', '#2a4055', '#5a8060', '#e8f0f8'],
    description: 'A genuine Australian black opal sits at the heart of this halo ring, displaying that prized dark body tone overlaid with vivid green-and-blue play of colour. A dense ring of pavé diamonds holds and amplifies every flash of light. Black opals from Lightning Ridge are the rarest opals in the world; each piece is one of a kind.',
    specifications: {
      stoneType: 'Natural Solid Black Opal',
      stoneOrigin: 'Lightning Ridge, NSW',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '2.0–2.8 ct',
      diamondQuality: 'VS clarity, F colour',
      settingStyle: 'Diamond Halo, Comfort-Fit Shank',
      careInstructions: 'Avoid extreme heat and chemicals. Clean with a soft damp cloth.'
    }
  },
  {
    id: 6,
    slug: 'paraiba-tone-halo-ring',
    name: 'Paraiba-Tone Tourmaline Halo Ring',
    sku: 'TG-TML-301',
    badge: null,
    gemstone: 'Tourmaline',
    gemColor: '#3aa090',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 2150,
    originalPrice: 2599,
    rating: 4.8,
    reviewCount: 78,
    images: ['assets/rings/IMG_9152.jpg', 'assets/rings/IMG_9163.jpg'],
    metals: ['14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.70', '0.88', '1.00'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.88',
    sizeOptions: STD_SIZES,
    swatchColors: ['#3aa090', '#5fc0b0', '#80d0c8', '#e8f0f8'],
    description: 'A captivating Paraiba-tone tourmaline cabochon glows with that signature electric teal you only see in fine green-blue tourmalines. The pavé diamond halo emphasises the saturation of the centre stone. A modern alternative to a sapphire or aquamarine centre.',
    specifications: {
      stoneType: 'Tourmaline (Paraiba-tone)',
      stoneOrigin: 'Brazil or Mozambique',
      stoneHardness: '7–7.5 Mohs',
      centerStoneApproxCarat: '1.8–2.4 ct',
      diamondQuality: 'VS clarity, G colour',
      settingStyle: 'Pavé Halo',
      careInstructions: 'Mild soap and warm water. Avoid steam cleaners.'
    }
  },
  {
    id: 7,
    slug: 'turquoise-opal-halo-ring',
    name: 'Turquoise Opal Halo Ring',
    sku: 'TG-OPL-104',
    badge: null,
    gemstone: 'Opal',
    gemColor: '#7ad0c0',
    shape: 'Oval',
    style: 'Halo',
    basePrice: 1980,
    originalPrice: 2399,
    rating: 4.7,
    reviewCount: 64,
    images: ['assets/rings/IMG_9153.jpg', 'assets/rings/IMG_9154.jpg', 'assets/rings/IMG_9155.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold'],
    qualities: ['Good (A)', 'Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.52', '0.70', '0.88'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Better (AA)',
    defaultCarat: '0.70',
    sizeOptions: STD_SIZES,
    swatchColors: ['#7ad0c0', '#a8e0d0', '#bfe8e0', '#e8f0f8'],
    description: 'Soft turquoise body tone with watery hints of green and blue — this opal halo ring is sweet, light and joyful. A delicate diamond halo and slim shank make it lovely as either a stand-alone fashion ring or an unconventional engagement piece for the colour-loving bride.',
    specifications: {
      stoneType: 'Natural Crystal Opal',
      stoneOrigin: 'Coober Pedy, SA',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '1.5–2.0 ct',
      diamondQuality: 'SI clarity, G-H colour',
      settingStyle: 'Halo with Slim Shank',
      careInstructions: 'Avoid heat and dehydration. Wipe clean with a soft cloth.'
    }
  },
  {
    id: 8,
    slug: 'white-opal-vintage-cluster-ring',
    name: 'White Opal Vintage Cluster Ring',
    sku: 'TG-OPL-105',
    badge: null,
    gemstone: 'Opal',
    gemColor: '#e8d8e8',
    shape: 'Oval',
    style: 'Vintage',
    basePrice: 1690,
    originalPrice: 1999,
    rating: 4.6,
    reviewCount: 51,
    images: ['assets/rings/IMG_9165.jpg', 'assets/rings/IMG_9166.jpg', 'assets/rings/IMG_9167.jpg'],
    metals: ['Sterling Silver', '14K White Gold'],
    qualities: ['Good (A)', 'Better (AA)'],
    caratOptions: ['0.52', '0.70', '0.88'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Better (AA)',
    defaultCarat: '0.70',
    sizeOptions: STD_SIZES,
    swatchColors: ['#e8d8e8', '#d0c0d0', '#fff5e8', '#e8f0f8'],
    description: 'A vintage-inspired cluster ring built around a milky white opal with subtle pinks and greens dancing across its surface. Side cluster diamonds and a millegrain edge give it that old-world look prized by collectors of antique-style pieces.',
    specifications: {
      stoneType: 'Natural White Opal',
      stoneOrigin: 'Coober Pedy, SA',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '1.6–2.2 ct',
      diamondQuality: 'SI clarity, H colour',
      settingStyle: 'Cluster with Millegrain Detail',
      careInstructions: 'Mild soap, lukewarm water, soft cloth only.'
    }
  },
  {
    id: 9,
    slug: 'black-opal-pear-cluster-ring',
    name: 'Black Opal Pear Cluster Statement Ring',
    sku: 'TG-OPL-106',
    badge: null,
    gemstone: 'Opal',
    gemColor: '#0e2828',
    shape: 'Pear',
    style: 'Cluster',
    basePrice: 2390,
    originalPrice: 2799,
    rating: 4.8,
    reviewCount: 72,
    images: ['assets/rings/IMG_9168.jpg', 'assets/rings/IMG_9174.jpg', 'assets/rings/IMG_9175.jpg'],
    metals: ['14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.70', '0.88', '1.00', '1.20'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.88',
    sizeOptions: STD_SIZES,
    swatchColors: ['#0e2828', '#1a3a3a', '#5a9080', '#e8f0f8'],
    description: 'A pear-shaped Australian black opal anchors this dramatic cluster, ringed in pavé diamonds and finished with split shoulders for extra fire. The deep body tone showcases the green-blue play of colour spectacularly. A true conversation piece.',
    specifications: {
      stoneType: 'Natural Solid Black Opal',
      stoneOrigin: 'Lightning Ridge, NSW',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '1.6–2.4 ct',
      diamondQuality: 'VS clarity, G colour',
      settingStyle: 'Pavé Cluster, Split Shoulder',
      careInstructions: 'Avoid harsh chemicals and ultrasonic. Soft cloth and warm soapy water.'
    }
  },
  {
    id: 10,
    slug: 'thin-sapphire-band',
    name: 'Petite Sapphire Solitaire Band',
    sku: 'TG-SPH-203',
    badge: null,
    gemstone: 'Sapphire',
    gemColor: '#1d3a78',
    shape: 'Round',
    style: 'Solitaire',
    basePrice: 850,
    originalPrice: 1099,
    rating: 4.7,
    reviewCount: 132,
    images: ['assets/rings/IMG_9143.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold'],
    qualities: ['Good (A)', 'Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.34', '0.52', '0.70'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Better (AA)',
    defaultCarat: '0.52',
    sizeOptions: STD_SIZES,
    swatchColors: ['#1d3a78', '#3070b0', '#e8f0f8'],
    description: 'A petite sapphire solitaire on an ultra-fine polished band — understated, comfortable, and absolutely elegant. Wears equally well stacked with other rings or worn alone as a quiet engagement piece.',
    specifications: {
      stoneType: 'Natural Blue Sapphire',
      stoneOrigin: 'Australia or Sri Lanka',
      stoneHardness: '9 Mohs',
      centerStoneApproxCarat: '0.4–0.6 ct',
      bandWidth: '1.6 mm',
      settingStyle: 'Four-Prong Solitaire',
      careInstructions: 'Daily wear safe. Clean with warm soapy water.'
    }
  },
  {
    id: 11,
    slug: 'small-opal-stud-ring',
    name: 'Mini Opal Stud Ring',
    sku: 'TG-OPL-107',
    badge: null,
    gemstone: 'Opal',
    gemColor: '#a8d4dc',
    shape: 'Oval',
    style: 'Solitaire',
    basePrice: 720,
    originalPrice: 899,
    rating: 4.6,
    reviewCount: 88,
    images: ['assets/rings/IMG_9144.jpg', 'assets/rings/IMG_9169.jpg'],
    metals: ['Sterling Silver', '14K White Gold'],
    qualities: ['Good (A)', 'Better (AA)'],
    caratOptions: ['0.34', '0.52'],
    defaultMetal: 'Sterling Silver',
    defaultQuality: 'Better (AA)',
    defaultCarat: '0.34',
    sizeOptions: STD_SIZES,
    swatchColors: ['#a8d4dc', '#d4d8e0', '#e0e8f0'],
    description: 'A simple, refined opal solitaire on a polished thin band. This is a lovely everyday piece or a sweet first-opal ring — light enough to stack with wedding bands, special enough to wear alone.',
    specifications: {
      stoneType: 'Natural Crystal Opal',
      stoneOrigin: 'Coober Pedy, SA',
      stoneHardness: '5.5–6.5 Mohs',
      centerStoneApproxCarat: '0.4–0.6 ct',
      bandWidth: '1.8 mm',
      settingStyle: 'Bezel Solitaire',
      careInstructions: 'Avoid harsh chemicals. Clean with a damp soft cloth.'
    }
  },
  {
    id: 12,
    slug: 'aqua-chalcedony-cocktail-ring',
    name: 'Aqua Chalcedony Cabochon Cocktail Ring',
    sku: 'TG-CHC-401',
    badge: 'NEW ARRIVAL',
    gemstone: 'Chalcedony',
    gemColor: '#9ed8e8',
    shape: 'Cushion',
    style: 'Fashion',
    basePrice: 1490,
    originalPrice: 1799,
    rating: 4.7,
    reviewCount: 56,
    images: ['assets/rings/IMG_9185.jpg', 'assets/rings/IMG_9186.jpg', 'assets/rings/IMG_9179.jpg'],
    metals: ['Sterling Silver', '14K White Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.50', '2.00'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#9ed8e8', '#b8e8f0', '#cfeff7', '#e8f0f8'],
    description: 'A generously sized cushion-cut aqua chalcedony cabochon glows with a soft watery blue. The smooth-domed cabochon cut emphasises the stone\'s milky luminescence rather than facets — a contemporary, modern look. Set in a tapered polished shank for clean, understated elegance.',
    specifications: {
      stoneType: 'Aqua Chalcedony',
      stoneOrigin: 'Brazil',
      stoneHardness: '6.5–7 Mohs',
      centerStoneApproxCarat: '6–8 ct',
      settingStyle: 'Bezel Set Cabochon',
      careInstructions: 'Clean with mild soap and warm water; avoid abrasives.'
    }
  },

  // ============================================================
  //  YELLOW GOLD COCKTAIL COLLECTION
  // ============================================================
  {
    id: 13,
    slug: 'citrine-emerald-cut-cocktail-ring',
    name: 'Emerald-Cut Madeira Citrine Cocktail Ring',
    sku: 'TG-CIT-501',
    badge: 'BEST SELLER',
    gemstone: 'Citrine',
    gemColor: '#c47a18',
    shape: 'Emerald Cut',
    style: 'Fashion',
    basePrice: 2390,
    originalPrice: 2799,
    rating: 4.8,
    reviewCount: 168,
    images: ['assets/rings/IMG_9190.jpg', 'assets/rings/IMG_9191.jpg', 'assets/rings/IMG_9192.jpg', 'assets/rings/IMG_9195.jpg', 'assets/rings/IMG_9196.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#c47a18', '#d68a28', '#e0a040', '#ffd700'],
    description: 'A spectacular emerald-cut Madeira citrine — that prized cognac-orange hue — set in warm yellow gold with a milgrain ornamental gallery. Step-cut facets reveal the stone\'s clarity and depth. Citrine is November\'s birthstone and is associated with abundance, energy and joy.',
    specifications: {
      stoneType: 'Natural Madeira Citrine',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '8–10 ct',
      settingStyle: 'Four-Prong with Filigree Gallery',
      metalFinish: 'High Polish with Milgrain Details',
      careInstructions: 'Daily wear safe. Clean with warm soapy water.'
    }
  },
  {
    id: 14,
    slug: 'huge-citrine-statement-ring',
    name: 'Statement Citrine Couture Ring',
    sku: 'TG-CIT-502',
    badge: 'NEW ARRIVAL',
    gemstone: 'Citrine',
    gemColor: '#d8901c',
    shape: 'Emerald Cut',
    style: 'Cocktail',
    basePrice: 2890,
    originalPrice: 3399,
    rating: 4.9,
    reviewCount: 91,
    images: ['assets/rings/IMG_9267.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Best (AAA)'],
    caratOptions: ['1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '2.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#d8901c', '#e8a03c', '#ffd700'],
    description: 'A bold, oversized faceted citrine in a sculpted gold throne setting with ornate scroll shoulders. This is a true couture cocktail piece — perfect for evenings where the outfit calls for a single, decisive ring.',
    specifications: {
      stoneType: 'Natural Citrine',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '14–18 ct',
      settingStyle: 'Sculpted Gold Throne with Scroll Shoulders',
      careInstructions: 'Wipe clean with a soft cloth. Avoid harsh chemicals.'
    }
  },
  {
    id: 15,
    slug: 'cognac-smoky-quartz-cocktail-ring',
    name: 'Cognac Smoky Quartz Cocktail Ring',
    sku: 'TG-SMQ-601',
    badge: 'BEST SELLER',
    gemstone: 'Smoky Quartz',
    gemColor: '#7a4a18',
    shape: 'Cushion',
    style: 'Cocktail',
    basePrice: 1980,
    originalPrice: 2399,
    rating: 4.8,
    reviewCount: 142,
    images: ['assets/rings/IMG_9232.jpg', 'assets/rings/IMG_9233.jpg', 'assets/rings/IMG_9234.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '2.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#7a4a18', '#9f6028', '#c47a18', '#ffd700'],
    description: 'A bold cushion-cut cognac smoky quartz set high in a polished yellow-gold scaffold. The deep amber-brown body and step-cut facets create a striking play of light. Smoky quartz is a member of the quartz family with excellent durability for a daily statement ring.',
    specifications: {
      stoneType: 'Natural Smoky Quartz',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '20–24 ct',
      settingStyle: 'Open Gallery, Tapered Shank',
      careInstructions: 'Daily wear safe. Avoid prolonged direct sunlight which may slightly fade the colour over years.'
    }
  },
  {
    id: 16,
    slug: 'cognac-quartz-east-west-ring',
    name: 'East-West Cognac Quartz Ring',
    sku: 'TG-SMQ-602',
    badge: null,
    gemstone: 'Smoky Quartz',
    gemColor: '#8a5828',
    shape: 'Cushion',
    style: 'Cocktail',
    basePrice: 1690,
    originalPrice: 1999,
    rating: 4.7,
    reviewCount: 73,
    images: ['assets/rings/IMG_9239.jpg', 'assets/rings/IMG_9240.jpg', 'assets/rings/IMG_9241.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.20', '1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#8a5828', '#a86838', '#c47a18'],
    description: 'A cushion-cut cognac quartz set in the modern east-west orientation that lengthens the finger and accentuates the stone\'s clarity. A clean, low-profile gold gallery completes a look that\'s contemporary yet warmly retro.',
    specifications: {
      stoneType: 'Natural Smoky Quartz',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '12–16 ct',
      settingStyle: 'East-West Bezel',
      careInstructions: 'Clean with mild soap and water.'
    }
  },
  {
    id: 17,
    slug: 'topaz-statement-ring',
    name: 'Smoky Topaz Filigree Statement Ring',
    sku: 'TG-TPZ-701',
    badge: null,
    gemstone: 'Topaz',
    gemColor: '#9a5028',
    shape: 'Cushion',
    style: 'Vintage',
    basePrice: 1580,
    originalPrice: 1899,
    rating: 4.7,
    reviewCount: 64,
    images: ['assets/rings/IMG_9237.jpg', 'assets/rings/IMG_9238.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.20', '1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#9a5028', '#b86838', '#d68a28'],
    description: 'A hand-finished vintage-style ring centred on a faceted smoky topaz with delicate gold filigree on the gallery and shoulders. The warm caramel tones make this a lovely autumn-into-winter cocktail ring.',
    specifications: {
      stoneType: 'Smoky Topaz',
      stoneOrigin: 'Brazil',
      stoneHardness: '8 Mohs',
      centerStoneApproxCarat: '6–8 ct',
      settingStyle: 'Filigree Gallery',
      careInstructions: 'Avoid sudden temperature changes. Clean with mild soap.'
    }
  },
  {
    id: 18,
    slug: 'amethyst-marquise-cluster-ring',
    name: 'Amethyst Marquise Cluster Ring',
    sku: 'TG-AMS-801',
    badge: null,
    gemstone: 'Amethyst',
    gemColor: '#7c3f8f',
    shape: 'Cluster',
    style: 'Vintage',
    basePrice: 1450,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 119,
    images: ['assets/rings/IMG_9209.jpg', 'assets/rings/IMG_9210.jpg', 'assets/rings/IMG_9211.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.88', '1.00', '1.20'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#7c3f8f', '#9050a8', '#a060c0', '#ffd700'],
    description: 'A burst of amethyst marquise stones set in a fan-shaped cluster, like a small bouquet on the finger. The yellow-gold setting warms the cool purple to give a true vintage Italian feel. Light, comfortable, and undeniably charming.',
    specifications: {
      stoneType: 'Amethyst (Quartz)',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '1.4–1.8 ct total',
      settingStyle: 'Fan-Cluster',
      careInstructions: 'Avoid prolonged sun exposure. Clean with mild soap.'
    }
  },
  {
    id: 19,
    slug: 'amethyst-fan-statement-ring',
    name: 'Amethyst Fan Statement Ring',
    sku: 'TG-AMS-802',
    badge: null,
    gemstone: 'Amethyst',
    gemColor: '#8a4ca0',
    shape: 'Cluster',
    style: 'Vintage',
    basePrice: 1690,
    originalPrice: 1999,
    rating: 4.7,
    reviewCount: 58,
    images: ['assets/rings/IMG_9230.jpg', 'assets/rings/IMG_9231.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Best (AAA)'],
    caratOptions: ['1.00', '1.20', '1.50'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.20',
    sizeOptions: STD_SIZES,
    swatchColors: ['#8a4ca0', '#a060c0', '#b870d0'],
    description: 'A wide fan of marquise-cut amethysts set on a polished yellow-gold band — a low-profile, eye-catching cocktail piece that sits flat enough for daily wear. Italian-style craftsmanship.',
    specifications: {
      stoneType: 'Amethyst',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '1.6–2.2 ct total',
      settingStyle: 'Fan Cluster',
      careInstructions: 'Mild soap and water.'
    }
  },
  {
    id: 20,
    slug: 'amethyst-cabochon-couture-ring',
    name: 'Amethyst Cabochon Couture Ring',
    sku: 'TG-AMS-803',
    badge: 'NEW ARRIVAL',
    gemstone: 'Amethyst',
    gemColor: '#6a2d80',
    shape: 'Oval',
    style: 'Cocktail',
    basePrice: 2280,
    originalPrice: 2699,
    rating: 4.8,
    reviewCount: 47,
    images: ['assets/rings/IMG_9271.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Best (AAA)'],
    caratOptions: ['1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '2.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#6a2d80', '#8040a0', '#a060c0'],
    description: 'A deep purple amethyst cabochon enthroned in an ornate carved gold setting with a sculpted gallery. Couture-style scale and craftsmanship make this the centrepiece of any evening ensemble.',
    specifications: {
      stoneType: 'Natural Amethyst',
      stoneOrigin: 'Uruguay',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '14–18 ct',
      settingStyle: 'Sculpted Gold Throne',
      careInstructions: 'Avoid heat and direct sun exposure.'
    }
  },
  {
    id: 21,
    slug: 'turquoise-cabochon-cocktail-ring',
    name: 'Persian Turquoise Cabochon Ring',
    sku: 'TG-TRQ-901',
    badge: null,
    gemstone: 'Turquoise',
    gemColor: '#4ab0c8',
    shape: 'Oval',
    style: 'Cocktail',
    basePrice: 1290,
    originalPrice: 1599,
    rating: 4.7,
    reviewCount: 86,
    images: ['assets/rings/IMG_9257.jpg', 'assets/rings/IMG_9258.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#4ab0c8', '#6cc0d8', '#9fdce8', '#ffd700'],
    description: 'A vibrant Persian-blue turquoise cabochon set in a high yellow-gold dome. Turquoise has been treasured since ancient Egypt and is December\'s birthstone. The warm gold and cool blue contrast beautifully on every skin tone.',
    specifications: {
      stoneType: 'Natural Turquoise',
      stoneOrigin: 'Iran (Persian) or Arizona',
      stoneHardness: '5–6 Mohs',
      centerStoneApproxCarat: '4–6 ct',
      settingStyle: 'High Bezel Cabochon',
      careInstructions: 'Avoid water immersion and oils. Wipe with a soft dry cloth.'
    }
  },
  {
    id: 22,
    slug: 'aqua-turquoise-statement-ring',
    name: 'Aqua Turquoise Statement Ring',
    sku: 'TG-TRQ-902',
    badge: null,
    gemstone: 'Turquoise',
    gemColor: '#5fc8d8',
    shape: 'Oval',
    style: 'Cocktail',
    basePrice: 1480,
    originalPrice: 1799,
    rating: 4.6,
    reviewCount: 41,
    images: ['assets/rings/IMG_9262.jpg', 'assets/rings/IMG_9263.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#5fc8d8', '#7fd8e8', '#9fdce8'],
    description: 'A bold sky-blue turquoise cabochon in a sculpted gold setting with a textured shank. The almost-aqua tone of this stone reads as a softer, more modern variation of classic Persian turquoise.',
    specifications: {
      stoneType: 'Natural Turquoise',
      stoneOrigin: 'Arizona, USA',
      stoneHardness: '5–6 Mohs',
      centerStoneApproxCarat: '6–8 ct',
      settingStyle: 'Sculpted Bezel',
      careInstructions: 'Wipe clean. Avoid oils, perfumes and prolonged water.'
    }
  },
  {
    id: 23,
    slug: 'gold-pearl-solitaire-ring',
    name: 'Akoya Pearl Solitaire Ring',
    sku: 'TG-PRL-1001',
    badge: null,
    gemstone: 'Pearl',
    gemColor: '#f4ecdc',
    shape: 'Round',
    style: 'Solitaire',
    basePrice: 980,
    originalPrice: 1199,
    rating: 4.7,
    reviewCount: 102,
    images: ['assets/rings/IMG_9272.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold', '14K White Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.50'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#f4ecdc', '#ffe8c8', '#e8e0d0'],
    description: 'A creamy Akoya pearl on a slim polished band — June\'s birthstone in its most classic, refined form. A perfect special-occasion ring or a graduation/engagement gift.',
    specifications: {
      stoneType: 'Cultured Akoya Pearl',
      stoneOrigin: 'Japan',
      pearlSize: '8.5–9.5 mm',
      lustreGrade: 'A+',
      settingStyle: 'Cup Set Solitaire',
      careInstructions: 'Wipe with a soft cloth after wear. Avoid perfumes and harsh chemicals.'
    }
  },
  {
    id: 24,
    slug: 'pink-tourmaline-cluster-ring',
    name: 'Pink Tourmaline Pavé Cluster Ring',
    sku: 'TG-TML-302',
    badge: 'BEST SELLER',
    gemstone: 'Tourmaline',
    gemColor: '#d65a8a',
    shape: 'Cluster',
    style: 'Cocktail',
    basePrice: 1390,
    originalPrice: 1699,
    rating: 4.8,
    reviewCount: 128,
    images: ['assets/rings/IMG_9283.jpg', 'assets/rings/IMG_9285.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.20', '1.50'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.20',
    sizeOptions: STD_SIZES,
    swatchColors: ['#d65a8a', '#e07ca8', '#e8a0c0', '#e8f0f8'],
    description: 'A dome of softly graduated pink tourmaline pavé set in a high cluster — like a tiny rose garden on the finger. Tourmaline is October\'s alternate birthstone and is renowned for its colour range; pink tourmalines symbolise compassion and joy.',
    specifications: {
      stoneType: 'Pink Tourmaline (Rubellite)',
      stoneOrigin: 'Brazil or Mozambique',
      stoneHardness: '7–7.5 Mohs',
      centerStoneApproxCarat: '1.4–1.8 ct total',
      settingStyle: 'Pavé Dome Cluster',
      careInstructions: 'Daily-wear safe. Mild soap and water.'
    }
  },
  {
    id: 25,
    slug: 'amber-cabochon-statement-ring',
    name: 'Amber Cabochon Statement Ring',
    sku: 'TG-AMB-1101',
    badge: null,
    gemstone: 'Amber',
    gemColor: '#b86818',
    shape: 'Oval',
    style: 'Cocktail',
    basePrice: 880,
    originalPrice: 1099,
    rating: 4.5,
    reviewCount: 39,
    images: ['assets/rings/IMG_9286.jpg', 'assets/rings/IMG_9288.jpg', 'assets/rings/IMG_9296.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Good (A)', 'Better (AA)'],
    caratOptions: ['1.50', '2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Better (AA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#b86818', '#d68a28', '#e8a040'],
    description: 'A glowing Baltic amber cabochon set high in a yellow-gold bezel with a textured rope shank. Lightweight and surprisingly comfortable for daily wear.',
    specifications: {
      stoneType: 'Baltic Amber',
      stoneOrigin: 'Baltic Sea region',
      stoneHardness: '2-2.5 Mohs',
      centerStoneApproxCarat: '8-12 ct',
      settingStyle: 'Bezel with Rope Shank',
      careInstructions: 'Soft, low hardness - avoid scratches. Wipe with a soft cloth only.'
    }
  },
  {
    id: 26,
    slug: 'opal-statement-trio-ring',
    name: 'Boulder Opal Statement Ring',
    sku: 'TG-OPL-108',
    badge: 'NEW ARRIVAL',
    gemstone: 'Opal',
    gemColor: '#5a9080',
    shape: 'Pear',
    style: 'Cocktail',
    basePrice: 2480,
    originalPrice: 2899,
    rating: 4.8,
    reviewCount: 38,
    images: ['assets/rings/IMG_9255.jpg', 'assets/rings/IMG_9256.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Best (AAA)'],
    caratOptions: ['2.00'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '2.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#5a9080', '#7fb8a8', '#a8d8c0', '#ffd700'],
    description: 'A freeform Australian boulder opal in a custom yellow-gold setting that wraps the natural ironstone matrix. Boulder opals are mined still attached to their host rock, giving every stone a one-of-a-kind landscape silhouette.',
    specifications: {
      stoneType: 'Australian Boulder Opal',
      stoneOrigin: 'Queensland',
      stoneHardness: '5.5-6.5 Mohs',
      centerStoneApproxCarat: '6-10 ct',
      settingStyle: 'Custom Open Bezel',
      careInstructions: 'Avoid heat and chemicals. Clean with a soft damp cloth.'
    }
  },
  {
    id: 27,
    slug: 'gold-onyx-signet-ring',
    name: 'Onyx Domed Signet Ring',
    sku: 'TG-SIG-1201',
    badge: null,
    gemstone: 'Black Onyx',
    gemColor: '#1a1a1a',
    shape: 'Signet',
    style: 'Statement',
    basePrice: 980,
    originalPrice: 1199,
    rating: 4.6,
    reviewCount: 92,
    images: ['assets/rings/IMG_9248.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#1a1a1a', '#ffed4e'],
    description: 'A polished domed black onyx set into a sculpted gold signet - a unisex piece that pairs equally well with cuffed shirts and stacked rings.',
    specifications: {
      stoneType: 'Black Onyx',
      stoneHardness: '6.5-7 Mohs',
      stoneSettingStyle: 'Bezel-Set Cabochon',
      bandWidth: '4-6 mm',
      finish: 'High Polish',
      careInstructions: 'Avoid scratches and harsh impacts. Soft cloth wipe.'
    }
  },
  {
    id: 28,
    slug: 'gold-citrine-cabochon-ring',
    name: 'Citrine Cabochon Cocktail Ring',
    sku: 'TG-CIT-503',
    badge: null,
    gemstone: 'Citrine',
    gemColor: '#d49a3c',
    shape: 'Oval',
    style: 'Cocktail',
    basePrice: 1090,
    originalPrice: 1299,
    rating: 4.6,
    reviewCount: 54,
    images: ['assets/rings/IMG_9323.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['1.00', '1.50'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.50',
    sizeOptions: STD_SIZES,
    swatchColors: ['#d49a3c', '#e8a850', '#ffc864'],
    description: 'A round citrine cabochon mounted in a textured yellow-gold cocktail setting. The cabochon cut showcases the smooth honey body of the stone.',
    specifications: {
      stoneType: 'Citrine',
      stoneOrigin: 'Brazil',
      stoneHardness: '7 Mohs',
      centerStoneApproxCarat: '4-6 ct',
      settingStyle: 'Bezel Cabochon',
      careInstructions: 'Daily wear safe. Soft cloth and mild soap.'
    }
  },
  {
    id: 29,
    slug: 'silver-eternity-multi-stone-ring',
    name: 'Multi-Gem Eternity Band',
    sku: 'TG-ETN-1301',
    badge: 'BEST SELLER',
    gemstone: 'Mixed Gems',
    gemColor: '#9bb5d8',
    shape: 'Band',
    style: 'Eternity',
    basePrice: 1290,
    originalPrice: 1599,
    rating: 4.9,
    reviewCount: 174,
    images: ['assets/rings/IMG_9282.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.88', '1.00', '1.20'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '1.00',
    sizeOptions: STD_SIZES,
    swatchColors: ['#9bb5d8', '#c0a0d0', '#a8d4dc', '#e8f0f8'],
    description: 'A wide eternity band channel-set with alternating opalescent and pastel gemstones around the entire circumference - a soft, light-catching ring that stacks beautifully with a plain band.',
    specifications: {
      stoneType: 'Mixed gems: opal, amethyst, topaz, peridot',
      settingStyle: 'Channel Set Eternity',
      bandWidth: '5-6 mm',
      careInstructions: 'Wipe clean. Avoid ultrasonic cleaning due to softer stones.'
    }
  },
  {
    id: 30,
    slug: 'silver-pave-band-ring',
    name: 'Diamond Pave Eternity Band',
    sku: 'TG-PVE-1401',
    badge: null,
    gemstone: 'Diamond',
    gemColor: '#e8f0f8',
    shape: 'Band',
    style: 'Eternity',
    basePrice: 1850,
    originalPrice: 2199,
    rating: 4.8,
    reviewCount: 109,
    images: ['assets/rings/IMG_9295.jpg', 'assets/rings/IMG_9207.jpg', 'assets/rings/IMG_9208.jpg'],
    metals: ['Sterling Silver', '14K White Gold', '18K White Gold', 'Platinum'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.52', '0.70', '0.88', '1.00'],
    defaultMetal: '14K White Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.70',
    sizeOptions: STD_SIZES,
    swatchColors: ['#e8f0f8', '#f4f4f4', '#cccccc'],
    description: 'A classic pave eternity ring set with a continuous line of small brilliant diamonds - versatile enough to wear as a wedding band, anniversary ring or standalone fashion piece.',
    specifications: {
      stoneType: 'Diamond',
      diamondQuality: 'VS-SI clarity, F-G colour',
      totalDiamondWeight: '0.5-1.0 ct.tw',
      settingStyle: 'Pave Eternity',
      bandWidth: '2.5-3 mm',
      careInstructions: 'Daily wear safe. Ultrasonic cleaning OK.'
    }
  },
  {
    id: 31,
    slug: 'thin-stackable-gold-band',
    name: 'Polished Thin Stackable Gold Band',
    sku: 'TG-BND-1501',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Stackable',
    basePrice: 580,
    originalPrice: 749,
    rating: 4.9,
    reviewCount: 246,
    images: ['assets/rings/IMG_9276.jpg', 'assets/rings/IMG_9320.jpg', 'assets/rings/IMG_9319.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold', '14K Rose Gold', '14K White Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#f4a460', '#e8e8e8'],
    description: 'A finely polished, ultra-slim gold band designed to stack endlessly. Wear three, five or seven together for the modern stacked-ring look.',
    specifications: {
      bandWidth: '1.4 mm',
      finish: 'High Polish',
      careInstructions: 'Daily wear safe. Mild soap and water.'
    }
  },
  {
    id: 32,
    slug: 'hammered-gold-statement-band',
    name: 'Hammered Gold Statement Band',
    sku: 'TG-BND-1502',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Fashion',
    basePrice: 1090,
    originalPrice: 1299,
    rating: 4.7,
    reviewCount: 73,
    images: ['assets/rings/IMG_9322.jpg', 'assets/rings/IMG_9318.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#daa520', '#ffed4e'],
    description: 'A medium-width yellow-gold band with a hand-hammered, textured finish. The artisanal surface catches light differently from a polished band.',
    specifications: {
      bandWidth: '4-5 mm',
      finish: 'Hand-Hammered',
      careInstructions: 'Soft cloth wipe. Avoid harsh polishes.'
    }
  },
  {
    id: 33,
    slug: 'gold-pave-band-ring',
    name: 'Gold Diamond Pave Band',
    sku: 'TG-PVE-1402',
    badge: 'BEST SELLER',
    gemstone: 'Diamond',
    gemColor: '#e8f0f8',
    shape: 'Band',
    style: 'Eternity',
    basePrice: 2480,
    originalPrice: 2899,
    rating: 4.9,
    reviewCount: 198,
    images: ['assets/rings/IMG_9348.jpg', 'assets/rings/IMG_9349.jpg', 'assets/rings/IMG_9350.jpg', 'assets/rings/IMG_9358.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold', '18K White Gold'],
    qualities: ['Best (AAA)'],
    caratOptions: ['0.52', '0.70', '0.88'],
    defaultMetal: '18K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.70',
    sizeOptions: STD_SIZES,
    swatchColors: ['#ffd700', '#ffed4e', '#e8f0f8'],
    description: 'A continuous yellow-gold band fully pave-set with brilliant diamonds - the modern wedding band reimagined.',
    specifications: {
      stoneType: 'Diamond',
      diamondQuality: 'VS-SI clarity, F-G colour',
      totalDiamondWeight: '0.5-0.9 ct.tw',
      settingStyle: 'Pave Eternity',
      bandWidth: '2.4 mm',
      careInstructions: 'Daily wear safe. Have prongs checked annually.'
    }
  },
  {
    id: 34,
    slug: 'religious-icon-signet-ring',
    name: 'Madonna Engraved Signet Ring',
    sku: 'TG-SIG-1202',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Signet',
    style: 'Statement',
    basePrice: 1490,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 36,
    images: ['assets/rings/IMG_9327.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '18K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: MEN_SIZES,
    swatchColors: ['#ffd700', '#daa520'],
    description: 'A bold rectangular yellow-gold signet engraved in deep relief with a Madonna and Child motif framed by a sunburst border.',
    specifications: {
      topSurfaceSize: '15 x 18 mm',
      bandWidth: '4-6 mm',
      engravingStyle: 'Deep Relief Casting',
      finish: 'High Polish with Textured Frame',
      careInstructions: 'Mild soap and water.'
    }
  },
  {
    id: 35,
    slug: 'small-ruby-signet-ring',
    name: 'Ruby Accent Patterned Signet',
    sku: 'TG-SIG-1203',
    badge: null,
    gemstone: 'Ruby',
    gemColor: '#c0182a',
    shape: 'Signet',
    style: 'Statement',
    basePrice: 1190,
    originalPrice: 1399,
    rating: 4.7,
    reviewCount: 44,
    images: ['assets/rings/IMG_9336.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.34', '0.52'],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.34',
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#c0182a', '#daa520'],
    description: 'A patterned yellow-gold signet centred on a small ruby accent. Ruby is Julys birthstone and symbolises love and good fortune.',
    specifications: {
      stoneType: 'Ruby',
      stoneHardness: '9 Mohs',
      centerStoneApproxCarat: '0.3-0.5 ct',
      settingStyle: 'Flush Set Bezel',
      careInstructions: 'Daily wear safe. Soft cloth and mild soap.'
    }
  },
  {
    id: 36,
    slug: 'patterned-gold-signet-ring',
    name: 'Patterned Wide Gold Signet',
    sku: 'TG-SIG-1204',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Signet',
    style: 'Statement',
    basePrice: 980,
    originalPrice: 1199,
    rating: 4.6,
    reviewCount: 28,
    images: ['assets/rings/IMG_9332.jpg', 'assets/rings/IMG_9333.jpg', 'assets/rings/IMG_9334.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: MEN_SIZES,
    swatchColors: ['#ffd700', '#daa520', '#ffed4e'],
    description: 'A wide patterned yellow-gold signet with a softly rounded square top and decorative engraved shoulders.',
    specifications: {
      topSurfaceSize: '11 x 12 mm',
      bandWidth: '4-6 mm',
      finish: 'High Polish + Engraved Shoulders',
      careInstructions: 'Daily wear safe.'
    }
  },
  {
    id: 37,
    slug: 'multi-band-gold-stack-ring',
    name: 'Trinity Multi-Band Gold Stack Ring',
    sku: 'TG-STK-1601',
    badge: 'NEW ARRIVAL',
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Stackable',
    basePrice: 1290,
    originalPrice: 1599,
    rating: 4.7,
    reviewCount: 62,
    images: ['assets/rings/IMG_9343.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: STD_SIZES,
    swatchColors: ['#ffd700', '#ffed4e', '#daa520'],
    description: 'A stack of fine yellow-gold bands joined as one ring - modern, voluminous, and perfect for filling out the finger. Inspired by Trinity-style stack rings.',
    specifications: {
      bandWidth: '8-10 mm overall',
      finish: 'High Polish',
      construction: 'Permanently joined multi-band stack',
      careInstructions: 'Mild soap and water.'
    }
  },
  {
    id: 38,
    slug: 'logo-engraved-band-ring',
    name: 'Engraved Iconic Logo Band',
    sku: 'TG-BND-1503',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Fashion',
    basePrice: 1890,
    originalPrice: 2299,
    rating: 4.7,
    reviewCount: 56,
    images: ['assets/rings/IMG_9360.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '18K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#ffed4e', '#daa520'],
    description: 'A wide yellow-gold band with engraved logo lettering inset into channels along both edges - designer aesthetic without the designer markup.',
    specifications: {
      bandWidth: '8-9 mm',
      finish: 'High Polish + Engraved Channels',
      careInstructions: 'Daily wear safe.'
    }
  },
  {
    id: 39,
    slug: 'two-tone-diamond-set-band',
    name: 'Two-Tone Diamond-Set Band',
    sku: 'TG-BND-1504',
    badge: null,
    gemstone: 'Diamond',
    gemColor: '#e8f0f8',
    shape: 'Band',
    style: 'Fashion',
    basePrice: 1690,
    originalPrice: 1999,
    rating: 4.7,
    reviewCount: 44,
    images: ['assets/rings/IMG_9361.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: ['Better (AA)', 'Best (AAA)'],
    caratOptions: ['0.34', '0.52'],
    defaultMetal: '18K Yellow Gold',
    defaultQuality: 'Best (AAA)',
    defaultCarat: '0.34',
    sizeOptions: STD_SIZES,
    swatchColors: ['#ffd700', '#e8f0f8'],
    description: 'A two-tone band: warm yellow-gold body with a contrasting white-gold diamond pave stripe. Modern, gender-neutral, and stacks effortlessly.',
    specifications: {
      stoneType: 'Diamond',
      diamondQuality: 'VS-SI clarity, G colour',
      totalDiamondWeight: '0.30-0.55 ct.tw',
      settingStyle: 'Pave Stripe',
      bandWidth: '4 mm',
      careInstructions: 'Daily wear safe.'
    }
  },
  {
    id: 40,
    slug: 'checkerboard-textured-band',
    name: 'Checkerboard Textured Band',
    sku: 'TG-BND-1505',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Fashion',
    basePrice: 1190,
    originalPrice: 1399,
    rating: 4.6,
    reviewCount: 38,
    images: ['assets/rings/IMG_9365.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: WIDE_SIZES,
    swatchColors: ['#ffd700', '#ffed4e'],
    description: 'A wide yellow-gold band with a finely engraved checkerboard texture across the front face. Catches light from many angles with a soft sparkle.',
    specifications: {
      bandWidth: '6-7 mm',
      finish: 'Engraved Checkerboard',
      careInstructions: 'Soft cloth wipe.'
    }
  },
  {
    id: 41,
    slug: 'sculptural-figure-statement-ring',
    name: 'Sculptural Figure Statement Ring',
    sku: 'TG-FIG-1701',
    badge: null,
    gemstone: 'None',
    gemColor: '#daa520',
    shape: 'Signet',
    style: 'Statement',
    basePrice: 1490,
    originalPrice: 1799,
    rating: 4.5,
    reviewCount: 24,
    images: ['assets/rings/IMG_9355.jpg', 'assets/rings/IMG_9353.jpg', 'assets/rings/IMG_9354.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '18K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: MEN_SIZES,
    swatchColors: ['#daa520', '#ffd700', '#b8860b'],
    description: 'A sculptural yellow-gold ring cast as a flowing figure - at once an art object and a wearable jewel. Hand-finished, generously sized.',
    specifications: {
      style: 'Sculpted Figural Casting',
      finish: 'High Polish',
      careInstructions: 'Mild soap and water. Soft cloth.'
    }
  },
  {
    id: 42,
    slug: 'pinky-detail-ring',
    name: 'Pinky Detail Ring',
    sku: 'TG-PNK-1801',
    badge: null,
    gemstone: 'None',
    gemColor: '#ffd700',
    shape: 'Band',
    style: 'Stackable',
    basePrice: 690,
    originalPrice: 849,
    rating: 4.5,
    reviewCount: 31,
    images: ['assets/rings/IMG_9363.jpg', 'assets/rings/IMG_9324.jpg', 'assets/rings/IMG_9325.jpg', 'assets/rings/IMG_9328.jpg'],
    metals: ['14K Yellow Gold', '18K Yellow Gold'],
    qualities: [],
    caratOptions: [],
    defaultMetal: '14K Yellow Gold',
    defaultQuality: null,
    defaultCarat: null,
    sizeOptions: [3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5],
    swatchColors: ['#ffd700', '#ffed4e', '#daa520'],
    description: 'A petite yellow-gold pinky ring with a soft top detail - a refined finishing touch when paired with bolder rings.',
    specifications: {
      bandWidth: '2.4 mm',
      finish: 'High Polish',
      careInstructions: 'Daily wear safe.'
    }
  }
];

const IMAGES = {
  sapphire:    'ring_sapphire_1775173368318.png',
  diamond:     'ring_diamond_1775173381818.png',
  emerald:     'ring_emerald_1775173397022.png',
  aquamarine:  'ring_aquamarine_1775173426942.png',
  ruby:        'ring_ruby_1775173443068.png',
  morganite:   'ring_morganite_1775173457195.png',
  tanzanite:   'ring_tanzanite_1775175245645.png',
  garnet:      'ring_garnet_1775175264227.png',
  amethyst:    'ring_amethyst_1775175279042.png',
  hand:        'ring_hand_lifestyle_1775175295636.png',
  side:        'ring_side_profile_1775175311559.png',
  dimension:   'ring_dimension_view_1775175410730.png',
  opalCat:     'rings/IMG_9151.jpg',
  citrineCat:  'rings/IMG_9190.jpg',
  amethystCat: 'rings/IMG_9271.jpg',
  smokyCat:    'rings/IMG_9232.jpg',
  turquoiseCat:'rings/IMG_9257.jpg',
  pearlCat:    'rings/IMG_9272.jpg',
  signetCat:   'rings/IMG_9327.jpg',
  bandCat:     'rings/IMG_9348.jpg',
  pinkCat:     'rings/IMG_9283.jpg',
  sapphireCat: 'rings/IMG_9145.jpg',
};

const img = (key) => `assets/${IMAGES[key] || key}`;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RINGS, METAL_MULTIPLIERS, QUALITY_MULTIPLIERS, CARAT_MULTIPLIERS, IMAGES, img };
}
